// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "MoveForward.h"
#define SECOND 50


MoveForward::MoveForward() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	speed = 0;
	done = false;
	counter = 0;
}

// Called just before this Command runs the first time
void MoveForward::Initialize() {
	speed = .1;
	done = false;
	counter = 0;
}

// Called repeatedly when this Command is scheduled to run
void MoveForward::Execute() {
	Robot::driveTrain->mecanum->MecanumDrive_Cartesian(0,.25,0);
	counter++;
}

// Make this return true when this Command no longer needs to run execute()
bool MoveForward::IsFinished() {

	if(counter > 50*3)
		return true;
	else
		return false;
}

// Called once after isFinished returns true
void MoveForward::End() {
	Robot::driveTrain->mecanum->MecanumDrive_Cartesian(0,0,0);
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveForward::Interrupted() {

}
