// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveTrain.h"
#include "Commands/PID.h"
#include "Commands/PistonToggle.h"
#include "Commands/lFirstToteLevel.h"
#include "Commands/lFourthToteLevel.h"
#include "Commands/lSecondToteLevel.h"
#include "Commands/lThirdToteLevel.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	xbox = new Joystick(0);
	
	fourthLevel = new JoystickButton(xbox, 8);
	fourthLevel->WhenPressed(new lFourthToteLevel());
	thirdLevel = new JoystickButton(xbox, 7);
	thirdLevel->WhenPressed(new lThirdToteLevel());
	secondLevel = new JoystickButton(xbox, 9);
	secondLevel->WhenPressed(new lSecondToteLevel());
	firstLevel = new JoystickButton(xbox, 10);
	firstLevel->WhenPressed(new lFirstToteLevel());
	pistonToggle = new JoystickButton(xbox, 1);
	pistonToggle->WhenPressed(new PistonToggle());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("Drive Train", new DriveTrain());

	SmartDashboard::PutData("Piston Toggle", new PistonToggle());

	SmartDashboard::PutData("PID", new PID());

	SmartDashboard::PutData("lFirstToteLevel", new lFirstToteLevel());

	SmartDashboard::PutData("lSecondToteLevel", new lSecondToteLevel());

	SmartDashboard::PutData("lThirdToteLevel", new lThirdToteLevel());

	SmartDashboard::PutData("lFourthToteLevel", new lFourthToteLevel());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getxbox() {
	return xbox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
