// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainLeftFront = NULL;
SpeedController* RobotMap::driveTrainLeftRear = NULL;
SpeedController* RobotMap::driveTrainRightFront = NULL;
SpeedController* RobotMap::driveTrainRightRear = NULL;
RobotDrive* RobotMap::driveTrainMecanum = NULL;
Gyro* RobotMap::driveTrainGyro = NULL;
Encoder* RobotMap::driveTrainDistanceMeasure = NULL;
Encoder* RobotMap::driveTrainRightEncoder = NULL;
Encoder* RobotMap::driveTrainLeftEncoder = NULL;
Solenoid* RobotMap::clamppiston = NULL;
Compressor* RobotMap::clampCompressor1 = NULL;
SpeedController* RobotMap::liftRlifter = NULL;
Encoder* RobotMap::liftRQuadratureEncoder = NULL;
DigitalInput* RobotMap::liftRAutonomousMode = NULL;
DigitalInput* RobotMap::liftRHomeSwitch = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainLeftFront = new Talon(4);
	lw->AddActuator("DriveTrain", "LeftFront", (Talon*) driveTrainLeftFront);
	
	driveTrainLeftRear = new Talon(2);
	lw->AddActuator("DriveTrain", "LeftRear", (Talon*) driveTrainLeftRear);
	
	driveTrainRightFront = new Talon(6);
	lw->AddActuator("DriveTrain", "RightFront", (Talon*) driveTrainRightFront);
	
	driveTrainRightRear = new Talon(3);
	lw->AddActuator("DriveTrain", "RightRear", (Talon*) driveTrainRightRear);
	
	driveTrainMecanum = new RobotDrive(driveTrainLeftFront, driveTrainLeftRear,
              driveTrainRightFront, driveTrainRightRear);
	
	driveTrainMecanum->SetSafetyEnabled(true);
        driveTrainMecanum->SetExpiration(0.1);
        driveTrainMecanum->SetSensitivity(0.5);
        driveTrainMecanum->SetMaxOutput(1.0);

        driveTrainMecanum->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        driveTrainMecanum->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
	driveTrainGyro = new Gyro(0);
	lw->AddSensor("DriveTrain", "Gyro ", driveTrainGyro);
	driveTrainGyro->SetSensitivity(0.007);
	driveTrainDistanceMeasure = new Encoder(2, 3, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "DistanceMeasure", driveTrainDistanceMeasure);
	driveTrainDistanceMeasure->SetDistancePerPulse(1.0);
        driveTrainDistanceMeasure->SetPIDSourceParameter(Encoder::kRate);
	driveTrainRightEncoder = new Encoder(6, 7, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "RightEncoder", driveTrainRightEncoder);
	driveTrainRightEncoder->SetDistancePerPulse(1.0);
        driveTrainRightEncoder->SetPIDSourceParameter(Encoder::kDistance);
	driveTrainLeftEncoder = new Encoder(8, 9, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "LeftEncoder", driveTrainLeftEncoder);
	driveTrainLeftEncoder->SetDistancePerPulse(1.0);
        driveTrainLeftEncoder->SetPIDSourceParameter(Encoder::kDistance);
	clamppiston = new Solenoid(0, 3);
	lw->AddActuator("Clamp", "piston", clamppiston);
	
	clampCompressor1 = new Compressor(0);
	
	
	liftRlifter = new Jaguar(1);
	lw->AddActuator("LiftR", "lifter", (Jaguar*) liftRlifter);
	
	liftRQuadratureEncoder = new Encoder(0, 1, false, Encoder::k4X);
	lw->AddSensor("LiftR", "QuadratureEncoder", liftRQuadratureEncoder);
	liftRQuadratureEncoder->SetDistancePerPulse(1.0);
        liftRQuadratureEncoder->SetPIDSourceParameter(Encoder::kDistance);
	liftRAutonomousMode = new DigitalInput(5);
	lw->AddSensor("LiftR", "AutonomousMode", liftRAutonomousMode);
	
	liftRHomeSwitch = new DigitalInput(4);
	lw->AddSensor("LiftR", "HomeSwitch", liftRHomeSwitch);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
