// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* driveTrainLeftFront;
	static SpeedController* driveTrainLeftRear;
	static SpeedController* driveTrainRightFront;
	static SpeedController* driveTrainRightRear;
	static RobotDrive* driveTrainMecanum;
	static Gyro* driveTrainGyro;
	static Encoder* driveTrainDistanceMeasure;
	static Encoder* driveTrainRightEncoder;
	static Encoder* driveTrainLeftEncoder;
	static Solenoid* clamppiston;
	static Compressor* clampCompressor1;
	static SpeedController* liftRlifter;
	static Encoder* liftRQuadratureEncoder;
	static DigitalInput* liftRAutonomousMode;
	static DigitalInput* liftRHomeSwitch;
	static DigitalInput* liftRAutonomousMode1;
	static DigitalInput* liftRAutonomousMode2;
	static DigitalInput* liftRAutonomousMode3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
